name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Set up SSH private key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.ENCODED_EC2_SSH_KEY }}" | base64 -d > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: SSH and deploy
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@3.38.25.129 << 'EOF'
          cd /home/ubuntu/codeplanner/Codeplanner_Backend
          git pull origin main
          npm install
          npm run build
          export NODE_ENV=production
          pm2 restart all
        EOF